## Week 7 - ANN



In [ ]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [18]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score

# 데이터 읽기 함수
def load_dataset(file):
  data = np.loadtxt(file)
  print("DATA=",data)
  
  input_features = data[:,0:-1] # 모든 행에 대하여, 맨 처음부터 뒤에서 두 번째까지 모두 가져와라 // 맨 마지막 열 빼고 입력값이기 때문
  print("X=",input_features)
  
  labels = np.reshape(data[:,-1],(4,1)) # 모든 행에 대하여 마지막 열을 (4행, 1열)로 바꾸어 가져옴 // 2차원으로 바꾸고 벡터화.
  print("Y=",labels)
 
  input_features = torch.tensor(input_features, dtype=torch.float)
  labels = torch.tensor(labels, dtype=torch.float)

  return (input_features, labels)

# 모델 평가 결과 계산을 위해 텐서를 리스트로 변환하는 함수
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

x, y = load_dataset("/gdrive/My Drive/ml_colab/week7/train.txt")
# 본 강의에서는 항상 load_dataset으로 할 것

# 2 by 2 matrix -> 정규 분포



# layer 1 가중치 초기화
w1 = torch.randn(2, 2, requires_grad=True) # requires_grad: gradient 전파 -> 이 값으로 인해 바뀌도록 (?)
b1 = torch.randn(2, requires_grad=True)

print("\n[Init]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))


# layer 2 가중치 초기화
w2 = torch.randn(2, 1, requires_grad=True)
b2 = torch.randn(1, requires_grad=True)

print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))



### 참고 - NA == 계산할 수 없음. (underflow 등의 이유)


# Activation 함수 설정
sigmoid = nn.Sigmoid()

# Cost 함수 - 이진분류 크로스엔트로피 비용 함수 설정 
loss_func = torch.nn.BCELoss()

# 옵티마이저 함수 (역전파 알고리즘을 수행할 함수)
optimizer = torch.optim.SGD([w1, b1, w2, b2], lr=0.05) # SGD - Stochastic Gradient Descent



""" 모델 학습 """
for epoch in range(1001):

    # H(X) 계산: forward 연산
    L2 = sigmoid(torch.add(torch.matmul(x, w1), b1)) # 1층
    hx = sigmoid(torch.add(torch.matmul(L2, w2), b2)) # 2층


    """ w, b 값 update 시작 """
    # 비용 계산
    cost = loss_func(hx, y)

    # 역전파 수행
    cost.backward()
    optimizer.step() # optimizer 실행
    """ w, b 값 update 끝 """
    # if cost 가 굉장히 작아져 0이랑 가가워지면 break


    # 100 에폭마다 비용 출력
    if epoch % 100 == 0:
        print(epoch, cost.item())

print("\n[Learned]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))
print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))


""" 모델 평가 """
# H(X) 계산: forward 연산
L2 = sigmoid(torch.add(torch.matmul(x, w1), b1))
hx = sigmoid(torch.add(torch.matmul(L2, w2), b2))


# hx는 1이 안 나옴. sigmoid 함수 결과 값이기 때문
logits = (hx > 0.5).float()
predicts = tensor2list(logits)
golds = tensor2list(y)


print("\nPRED=",predicts)
print("GOLD=",golds)
print("Accuracy : {0:f}".format(accuracy_score(golds, predicts)))

DATA= [[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
X= [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Y= [[0.]
 [1.]
 [1.]
 [0.]]

[Init]
w1 = [[-1.6039015054702759, 0.9669446349143982], [1.6664398908615112, -0.37710168957710266]]
b1 = [-0.9097310900688171, 0.5180159211158752]
w2 = [[0.09386227279901505], [1.209526777267456]]
b2 = [-0.530109167098999]

0 0.7102298736572266
100 0.5373131036758423
200 0.09103536605834961
300 4.188831735518761e-05
400 5.066399353381712e-07
500 8.940698137394065e-08
600 2.9802322387695312e-08
700 0.0
800 0.0
900 0.0
1000 0.0

[Learned]
w1 = [[-69.9582748413086, 60.21929931640625], [67.64826965332031, -96.91239166259766]]
b1 = [-58.37643814086914, -40.59731674194336]
w2 = [[83.81919860839844], [125.75112915039062]]
b2 = [-62.66192626953125]


PRED= [[0.0], [1.0], [1.0], [0.0]]
GOLD= [[0.0], [1.0], [1.0], [0.0]]
Accuracy : 1.000000
